// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"encore.dev/types/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description string
	TokenHash   string
	ValidUntil  pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	Roles        []string
	PasswordHash []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
